TESTS			 = test_io benchmark_disks flushbuffers
TESTS_NON_MSVC		 = sd_test
TESTS_UNITTEST		 = unittest

LIB_SRC			 = \
	iostats.cpp \
	diskqueue.cpp \
	request.cpp \
	request_waiters_impl_basic.cpp \
	request_state_impl_basic.cpp \
	request_impl_basic.cpp \
	file_request_basic.cpp \
	ufs_file.cpp \
	syscall_file.cpp \
	mmap_file.cpp \
	simdisk_file.cpp \
	wfs_file.cpp \
	wincall_file.cpp \
	boostfd_file.cpp \
	mem_file.cpp
