TESTS			 = test_scan gen_file test_sort test_ksort test_stable_ksort sort_file test_manyunits test_random_shuffle 
TESTS_LONG_COMPILE	 = test_sort_all_parameters test_ksort_all_parameters test_stable_ksort_all_parameters
TESTS_EXTRA		 = test_asch

LIB_SRC			 = async_schedule.cpp
