TESTS			 = test_scan gen_file sort_file test_ksort1 test_stable_ksort test_sort1 test_manyunits test_random_shuffle 
TESTS_LONG_COMPILE	 = test_ksort test_sort test_stable_ksort1
TESTS_EXTRA		 = test test_asch

LIB_SRC			 = async_schedule.cpp
